### ISSUE TITLE
0 files in total

### ISSUE THREAD

**Issue by Gisbert12843** [russo-2025/papyrus-compiler#6]
doesnt do anything when i run it like this:

papyrus compile -nocache -h "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Source\Scripts" -o "../compiled"

Output is:

C:\Users\Kai\Desktop\papyrus-compiler>papyrus compile -nocache -h "C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Source\Scripts" -o "../compiled"
used header dirs ['C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data\Source\Scripts']
0 files in total
parse files: 0.001 ms
parse headers files: 0.001 ms
check files: 0.0 ms
gen files: 0.004 ms
finish 1.255 ms

Maybe some Error Messages would be advisable.

**Comment by russo-2025** [comment]
Yes, an error message is indeed missing here. Thanks.
