### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by fefe17** [russo-2025/papyrus-compiler#7]
I'm trying to compile the git head of this project with a fresh git head build of v:

```$ ../v/v compiler.v
modules/pex/str.v:205:3: error: reference field must be initialized with reference
  203 | pub fn (p PexFile) str() string {
  204 |     mut b := PexStrBuilder {
  205 |         pex_file: p
      |         ~~~~~~~~~~~
  206 |         builder: strings.new_builder(4000)
  207 |     }
$
```

**Comment by russo-2025** [comment]
fixed

**Comment by fefe17** [comment]
I just used your compiler for the first time, to fix a problem in a script from a mod I had installed.

Not only did it work basically on the first try, it was an order of magnitude faster than the bethesda compiler.
Thank you for your contribution, sir. It has been a pleasure. Starred.
